version: 2
project_name: mackerel-plugin-litestream

before:
  hooks:
    - go mod tidy

builds:
  - id: mackerel-plugin-litestream
    binary: mackerel-plugin-litestream
    main: .
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

# mkr plugin install は `<repo>_<GOOS>_<GOARCH>.zip` の形式を要求します。
archives:
  - id: mackerel-plugin-litestream
    formats:
      - zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README*
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs?:'
      - '^test:'

release:
  github:
    owner: sh0jitmy
    name: mackerel-plugin-litestream
  draft: false
  replace_existing_artifacts: true

